### ISSUE TITLE
Add GTDBTk rule parameters by default

### ISSUE THREAD

**Issue by OmkarSaMo** [NBChub/bgcflow#208]
https://github.com/NBChub/bgcflow/blob/75bd932374930de64a4718d46048662cad8a84ab/.examples/_config_example.yaml#L63

@matinnuhamunada do you think it would make sense to add 207 release as default option here in the rule_parametes? 

Alternatively you can add these and comment them out. I have realized that sometimes users may not be aware that rule parameters can be changes in config yaml file readily

```
rule_parameters:
  install_gtdbtk:
    release: '207'
    release_version: 207_v2
```
