### ISSUE TITLE
How to use Custom input directory?

### ISSUE THREAD

**Issue by 540889956** [NBChub/bgcflow#349]
Hi,

I just wish to know how to use Custom input directory. And why this workflow can still running after I delete all the input files?

Step 2.1 Getting sample information from: config/Lactobacillus_delbrueckii/project_config.yaml
 - Processing project [config/Lactobacillus_delbrueckii/project_config.yaml]
 - Custom input directory: False
 - Getting input files from: /media/nick/Data/bgcflow/data/raw/fasta
 - Custom input format: False
 - Default input file type: fna

Thanks for your help in advance.

BW
WJ

**Comment by matinnuhamunada** [comment]
Hi, thanks for reaching out and using BGCFlow :)

### _I just wish to know how to use Custom input directory_

To use custom input directory, you will need to set up two things:

- Defining the input directory path (and maybe the input file type) in the project configuration (`project_config.yaml`)
- Adding your custom input samples in the `samples.csv`

Please find the example here: [config.zip](https://github.com/user-attachments/files/15811549/config.zip)

This is how the project structure will look like:
```bash
config/
├── Lactobacillus_delbrueckii
│   ├── input_files # your custom input directory
│   │   └── my_custom_genome.gbk
│   ├── gtdbtk.bac120.summary.tsv # an optional GTDB-tk style taxonomic assignment
│   ├── project_config.yaml # project level configuration, the rule set here will override the global parameter
│   └── samples.csv
└──── config.yaml # global parameter configuration
```

And this is how the project configuration (`project_config.yaml`) looks like:
```yaml
name: Lactobacillus_delbrueckii_custom_input

pep_version: 2.1.0

description: "An example of using custom input files in BGCFlow projects."
input_folder: input_files # This is the folder where the input files are located, relative to this file.
input_type: gbk # This is the default type of input files. It can be gbk or fna. Note that samples from NCBI will default to fna format.
gtdb-tax: gtdbtk.bac120.summary.tsv # you can also provide a custom GTDB-tk output style taxonomy information
sample_table: samples.csv

#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: TRUE
...
```
and finally, you need to add the custom sample in the `samples.csv`:

| genome_id         | source | organism | genus | species | strain | closest_placement_reference | input_file            |
|-------------------|--------|----------|-------|---------|--------|-----------------------------|-----------------------|
| GCA_000056065.1   | ncbi   |          |       |         |        |                             |                       |
| GCA_000182835.1   | ncbi   |          |       |         |        |                             |                       |
| GCA_000191165.1   | ncbi   |          |       |         |        |                             |                       |
| GCA_000014405.1   | ncbi   |          |       |         |        |                             |                       |
| strain_01         | custom |          |       |         |        |                             | my_custom_genome.gbk  |

and you should get this message:

```bash
Step 2.1 Getting sample information from: config/Lactobacillus_delbrueckii/project_config.yaml
 - Processing project [config/Lactobacillus_delbrueckii/project_config.yaml]
 - Custom input directory: True
 - Getting input files from: /datadrive/bgcflow/config/Lactobacillus_delbrueckii/input_files
 - Custom input format: True
 - Default input file type: gbk
   - ! WARNING: GCA_000056065.1 is from ncbi. Enforcing format to `fna`.
   - ! WARNING: GCA_000182835.1 is from ncbi. Enforcing format to `fna`.
   - ! WARNING: GCA_000191165.1 is from ncbi. Enforcing format to `fna`.
   - ! WARNING: GCA_000014405.1 is from ncbi. Enforcing format to `fna`.
 - Found user-provided taxonomic information
```

### _Why this workflow can still running after I delete all the input files?_
I would assume that you don't change anything in the example template configuration and only deleted the default input files located in `data/raw`. If this is the case, then the project can still run because all the samples are being fetched online from NCBI. You can check if this is the case from the `samples.csv`

Thank you again for the question, we will be sure to add this to the FAQ section and improve the WIKI.
